/*
 * Automatically generated C config: don't edit
 */

#define CONFIG_PPC 1
#define CONFIG_QEMU 1
#define CONFIG_BIG_ENDIAN 1
#define CONFIG_DEBUG 1
#undef  CONFIG_DEBUG_BOOT
#undef  CONFIG_DEBUG_DSTACK
#undef  CONFIG_DEBUG_RSTACK
#undef  CONFIG_DEBUG_DICTIONARY
#undef  CONFIG_DEBUG_INTERNAL
#undef  CONFIG_DEBUG_INTERPRETER
#define CONFIG_DEBUG_CONSOLE 1
#define CONFIG_DEBUG_CONSOLE_SERIAL 1
#define CONFIG_DRIVER_PC_SERIAL 1
#define CONFIG_DRIVER_PC_KBD 1
#define CONFIG_SERIAL_PORT 0
#define CONFIG_SERIAL_SPEED 115200
#define CONFIG_DEBUG_CONSOLE_VGA 1
#undef  CONFIG_DEBUG_OFMEM
#define CONFIG_CMDLINE 1
#define CONFIG_DEBLOCKER 1
#define CONFIG_FONT_8X8 1
#undef  CONFIG_FONT_8X16
#define CONFIG_OFMEM 1
#define CONFIG_OFMEM_MALLOC_ALIGN 4
#define CONFIG_VGA_WIDTH 800
#define CONFIG_VGA_HEIGHT 600
#define CONFIG_VGA_DEPTH 8
#undef  CONFIG_LOADER_AOUT
#define CONFIG_LOADER_BOOTINFO 1
#define CONFIG_LOADER_BOOTCODE 1
#define CONFIG_LOADER_ELF 1
#undef  CONFIG_LOADER_FCODE
#undef  CONFIG_LOADER_FORTH
#define CONFIG_LOADER_PREP 1
#define CONFIG_LOADER_XCOFF 1
#define CONFIG_DISK_LABEL 1
#define CONFIG_PART_SUPPORT 1
#define CONFIG_MAC_PARTS 1
#undef  CONFIG_DEBUG_MAC_PARTS
#define CONFIG_PC_PARTS 1
#define CONFIG_HFS 1
#define CONFIG_HFSP 1
#define CONFIG_ISO9660 1
#define CONFIG_EXT2 1
#define CONFIG_GRUBFS 1
#undef  CONFIG_FSYS_EXT2FS
#undef  CONFIG_FSYS_FAT
#undef  CONFIG_FSYS_JFS
#undef  CONFIG_FSYS_MINIX
#undef  CONFIG_FSYS_REISERFS
#undef  CONFIG_FSYS_XFS
#undef  CONFIG_FSYS_UFS
#undef  CONFIG_FSYS_ISO9660
#undef  CONFIG_FSYS_FFS
#undef  CONFIG_FSYS_VSTAFS
#undef  CONFIG_FSYS_NTFS
#undef  CONFIG_FSYS_AFFS
#undef  CONFIG_DEBUG_FS
#define CONFIG_PPC_64BITSUPPORT 1
#undef  CONFIG_LINUXBIOS
#undef  CONFIG_RTAS
#define CONFIG_LOCALS 1
#define CONFIG_DRIVER_PCI 1
#undef  CONFIG_DEBUG_PCI
#define CONFIG_DRIVER_IDE 1
#define CONFIG_IDE_NUM_CHANNELS 2
#define CONFIG_IDE_FIRST_UNIT 1
#define CONFIG_IDE_DEV_NAME  "ata" 
#define CONFIG_IDE_DEV_TYPE  "ata" 
#undef  CONFIG_DEBUG_IDE
#define CONFIG_DRIVER_ADB 1
#define CONFIG_DRIVER_VGA 1
#define CONFIG_DRIVER_MACIO 1
#define CONFIG_DRIVER_ESCC 1
#define CONFIG_DRIVER_FW_CFG 1
#define CONFIG_FW_CFG_ADDR 0xf0000510
#define CONFIG_DRIVER_USB 1
#undef  CONFIG_DEBUG_USB
#define CONFIG_USB_HID 1
#define CONFIG_DRIVER_LSI_53C810 1
#define CONFIG_DRIVER_VIRTIO_BLK 1
